services:
  web-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: web-api
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    command: npm run dev

